# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PAI_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setObjectName("pushButton_open")
        self.verticalLayout.addWidget(self.pushButton_open)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.lineEdit_filename = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_filename.setReadOnly(True)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.horizontalLayout.addWidget(self.lineEdit_filename)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_size1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_size1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_size1.setObjectName("lineEdit_size1")
        self.horizontalLayout_2.addWidget(self.lineEdit_size1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_size2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_size2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_size2.setObjectName("lineEdit_size2")
        self.horizontalLayout_2.addWidget(self.lineEdit_size2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_size3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_size3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_size3.setObjectName("lineEdit_size3")
        self.horizontalLayout_2.addWidget(self.lineEdit_size3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_flow = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_flow.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_flow.setObjectName("lineEdit_flow")
        self.horizontalLayout_6.addWidget(self.lineEdit_flow, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_fhigh = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fhigh.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_fhigh.setObjectName("lineEdit_fhigh")
        self.horizontalLayout_7.addWidget(self.lineEdit_fhigh)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_fsampling = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fsampling.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_fsampling.setObjectName("lineEdit_fsampling")
        self.horizontalLayout_8.addWidget(self.lineEdit_fsampling)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.comboBox_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_type.setEnabled(True)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_type)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setEnabled(True)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(20)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_10.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_auto_f = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_auto_f.setObjectName("pushButton_auto_f")
        self.horizontalLayout_16.addWidget(self.pushButton_auto_f)
        self.pushButton_Run_pre = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Run_pre.setObjectName("pushButton_Run_pre")
        self.horizontalLayout_16.addWidget(self.pushButton_Run_pre)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.Plot_Histogram = MplWidget(self.centralwidget)
        self.Plot_Histogram.setObjectName("Plot_Histogram")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.Plot_Histogram)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_5.addWidget(self.Plot_Histogram)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.verticalLayout_5.setStretch(1, 4)
        self.verticalLayout_5.setStretch(2, 1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_11.addWidget(self.line)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_4)
        self.comboBoxCmaps = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxCmaps.setObjectName("comboBoxCmaps")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxCmaps)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.Plot_Visual = MplWidget(self.centralwidget)
        self.Plot_Visual.setObjectName("Plot_Visual")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Plot_Visual)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4.addWidget(self.Plot_Visual)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.horizontalSlider_min = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_min.setMaximum(1000)
        self.horizontalSlider_min.setSingleStep(1)
        self.horizontalSlider_min.setProperty("value", 0)
        self.horizontalSlider_min.setSliderPosition(0)
        self.horizontalSlider_min.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_min.setObjectName("horizontalSlider_min")
        self.horizontalLayout_18.addWidget(self.horizontalSlider_min)
        self.lineEdit_min_scroll = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_min_scroll.setReadOnly(True)
        self.lineEdit_min_scroll.setObjectName("lineEdit_min_scroll")
        self.horizontalLayout_18.addWidget(self.lineEdit_min_scroll)
        self.horizontalLayout_18.setStretch(1, 10)
        self.horizontalLayout_18.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.horizontalSlider_max = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_max.setMaximum(1000)
        self.horizontalSlider_max.setSingleStep(1)
        self.horizontalSlider_max.setSliderPosition(1000)
        self.horizontalSlider_max.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_max.setObjectName("horizontalSlider_max")
        self.horizontalLayout_19.addWidget(self.horizontalSlider_max)
        self.lineEdit_max_scroll = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_max_scroll.setReadOnly(True)
        self.lineEdit_max_scroll.setObjectName("lineEdit_max_scroll")
        self.horizontalLayout_19.addWidget(self.lineEdit_max_scroll)
        self.horizontalLayout_19.setStretch(1, 10)
        self.horizontalLayout_19.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.pushButton_Expand = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Expand.setObjectName("pushButton_Expand")
        self.horizontalLayout_5.addWidget(self.pushButton_Expand)
        self.horizontalLayout_5.setStretch(0, 12)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_5)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setEnabled(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.spinBox_slice = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_slice.setEnabled(False)
        self.spinBox_slice.setObjectName("spinBox_slice")
        self.horizontalLayout_15.addWidget(self.spinBox_slice)
        self.horizontalLayout_15.setStretch(1, 2)
        self.horizontalLayout_15.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_3.addWidget(self.label_24)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_2)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.spinBox_patch_distance = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_patch_distance.setProperty("value", 9)
        self.spinBox_patch_distance.setObjectName("spinBox_patch_distance")
        self.horizontalLayout_13.addWidget(self.spinBox_patch_distance)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_13.addWidget(self.label_27)
        self.lineEdit_h = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_h.setObjectName("lineEdit_h")
        self.horizontalLayout_13.addWidget(self.lineEdit_h)
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_13.addWidget(self.label_35)
        self.horizontalLayout_13.setStretch(1, 1)
        self.horizontalLayout_13.setStretch(3, 1)
        self.horizontalLayout_13.setStretch(5, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_14.addWidget(self.pushButton)
        self.pushButton_denoising = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_denoising.setFont(font)
        self.pushButton_denoising.setObjectName("pushButton_denoising")
        self.horizontalLayout_14.addWidget(self.pushButton_denoising)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.setStretch(0, 1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(2, 2)
        self.gridLayout.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_open.setText(_translate("MainWindow", "Load Raw Data"))
        self.label_20.setText(_translate("MainWindow", "File name"))
        self.label_3.setText(_translate("MainWindow", "Pixel z"))
        self.label_4.setText(_translate("MainWindow", "Pixel x"))
        self.label_5.setText(_translate("MainWindow", "Pixel y"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Preprocessing</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Low Frequency (MHz)"))
        self.label_7.setText(_translate("MainWindow", "High Frequency (MHz)"))
        self.label_8.setText(_translate("MainWindow", "Sampling Frequency (MHz)"))
        self.label_11.setText(_translate("MainWindow", "Type of Band Pass"))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "Filtfilt"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "Lfilter"))
        self.label_12.setText(_translate("MainWindow", "Order of Band Pass"))
        self.pushButton_auto_f.setText(_translate("MainWindow", "Default MPA !"))
        self.pushButton_Run_pre.setText(_translate("MainWindow", "Run Preprocessing"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt;\">Siregar S, Nagaoka R, Haq IU, Saijo Y.</span></p><p align=\"center\"><span style=\" font-size:7pt;\">Non local means denoising in photoacoustic imaging. </span></p><p align=\"center\"><span style=\" font-size:7pt;\">Japanese Journal of Applied Physics.2018 Apr 19;57(7S1):07LB06.</span></p><p align=\"center\"><span style=\" font-size:7pt;\">Email : kucing.kuantum@gmail.com web : radio.kuantum.wordpress.com</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Visualtization"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Raw Image"))
        self.comboBoxCmaps.setItemText(0, _translate("MainWindow", "jet"))
        self.comboBoxCmaps.setItemText(1, _translate("MainWindow", "copper"))
        self.comboBoxCmaps.setItemText(2, _translate("MainWindow", "gray"))
        self.comboBoxCmaps.setItemText(3, _translate("MainWindow", "hsv"))
        self.comboBoxCmaps.setItemText(4, _translate("MainWindow", "hot"))
        self.comboBoxCmaps.setItemText(5, _translate("MainWindow", "cool"))
        self.comboBoxCmaps.setItemText(6, _translate("MainWindow", "summer"))
        self.comboBoxCmaps.setItemText(7, _translate("MainWindow", "winter"))
        self.comboBoxCmaps.setItemText(8, _translate("MainWindow", "autumn"))
        self.comboBoxCmaps.setItemText(9, _translate("MainWindow", "Set1"))
        self.comboBoxCmaps.setItemText(10, _translate("MainWindow", "gnuplot"))
        self.comboBoxCmaps.setItemText(11, _translate("MainWindow", "rainbow"))
        self.comboBoxCmaps.setItemText(12, _translate("MainWindow", "seismic"))
        self.comboBoxCmaps.setItemText(13, _translate("MainWindow", "pink"))
        self.comboBoxCmaps.setItemText(14, _translate("MainWindow", "spring"))
        self.comboBoxCmaps.setItemText(15, _translate("MainWindow", "Reds"))
        self.label_29.setText(_translate("MainWindow", "Minimum"))
        self.lineEdit_min_scroll.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "Maximum"))
        self.lineEdit_max_scroll.setText(_translate("MainWindow", "1"))
        self.pushButton_Expand.setText(_translate("MainWindow", "Expand Image"))
        self.label_18.setText(_translate("MainWindow", "Reconstruction"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "C mode"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "B mode MIP (Max. Intensity Projection)"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "B mode"))
        self.label_19.setText(_translate("MainWindow", "No. Slices For B mode"))
        self.label_24.setText(_translate("MainWindow", "Denoising Method Using Non-Local-Means Denoising"))
        self.label_25.setText(_translate("MainWindow", "Patch Size"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "3 X 3"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "5 X 5"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "7 X 7"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "9 X 9"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "11 X 11"))
        self.label_26.setText(_translate("MainWindow", "Patch Distance"))
        self.label_27.setText(_translate("MainWindow", "h "))
        self.label_35.setText(_translate("MainWindow", "sigma"))
        self.pushButton.setText(_translate("MainWindow", "Default Parameter"))
        self.pushButton_denoising.setText(_translate("MainWindow", "Calculate The Filtering"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

